---
title: "Simple Plots in R"
author: "Joshua Oluoch"
date: "1/31/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Plotting in R (Using Default Graphics Package)

This is a simple plotting in R manual. Consider the examples below:

No 1: **Pie Chart**

```{r pie}
x = c(23,87,35,90)
town <- c("Nakuru","Mombasa","Kisumu","Nairobi")
piepercent<- round(100*x/sum(x), 1)
pie(x, labels = piepercent, main = "City pie chart",col = rainbow(length(x)))
legend("topright", town, cex = 0.8,fill = rainbow(length(x)))
```


No 2: **Bar Plot**
```{r bar}
rev_in_Billions <- c(12.2,34,23,16,19)
months <- c("Jan","Feb","Mar","Apr","May")
barplot(rev_in_Billions,names.arg=months,xlab="Month",ylab="Revenue In Billions (KES)",col="green",
main="Revenue chart",border="red")
```




No 3: **Histogram**
```{r hist}
sample_data <- c(9,13,21,8,36,22,12,41,31,33,19)
hist(sample_data,xlab = "Weight",col = "green",border = "red", xlim = c(0,40), ylim = c(0,5),
   breaks = 5)
```





No 4: **Line Charts**
```{r line_chart}
x = round(runif(12,min = 0, max = 50),1) #This is used to generate random numbers
plot(x,type = "o", col = "red", xlab = "Month", ylab = "Rain fall",
   main = "Rain fall chart")
```

